version: '3.8'

services:
#  auth-pg:
#    image: postgres:14.1-alpine
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - '5432:5432'
#    volumes:
#      - pg:/var/lib/postgresql/data
#
#  auth-mongo:
#    image: mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: mongo
#      MONGO_INITDB_ROOT_PASSWORD: mongo

  auth:
    image: service-auth
    ports:
      - "3333:3333"
#    depends_on:
#      - auth-mongo

#volumes:
#  pg:
#    driver: local
