version: "3.8"

services:
  pg:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg:
    driver: local
