version: '3.8'

services:
#  auth-pg:
#    image: postgres:14.1-alpine
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - '5432:5432'
#    volumes:
#      - pg:/var/lib/postgresql/data

  auth-mongo:
    image: mongo:5
    restart: always
    ports:
      - '27014:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
#  pg:
#    image: postgres:14.1-alpine
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - '5432:5432'
#    volumes:
#      - pg:/var/lib/postgresql/data

#  reverse-proxy:
#    image: nginx:1.21-alpine
#    volumes:
#      - ./templates:/etc/nginx/templates
#    ports:
#      - '8080:80'
#    environment:
#      - NGINX_HOST=e-commerce.dev
#      - NGINX_PORT=80

#  reverse-proxy:
#    image: 'jc21/nginx-proxy-manager:latest'
#    restart: unless-stopped
#    ports:
#      - '80:80'
#      - '81:81'
#      - '443:443'
#    volumes:
#      - ./data:/data
#      - ./letsencrypt:/etc/letsencrypt

#volumes:
#  pg:
#    driver: local
