version: '3.8'

services:
#  auth-pg:
#    image: postgres:14.1-alpine
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - '5432:5432'
#    volumes:
#      - pg:/var/lib/postgresql/data

  auth-mongo:
    image: mongo:5
    restart: always
    ports:
      - '27014:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  orders-mongo:
    image: mongo:5
    restart: always
    ports:
      - '27015:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

#  pg:
#    image: postgres:14.1-alpine
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - '5432:5432'
#    volumes:
#      - pg:/var/lib/postgresql/data

#volumes:
#  pg:
#    driver: local
