apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: webtechnelson/client:latest
          imagePullPolicy: Always
          env:
            - name: UNSPLASH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: unsplash-client-id-secret
                  key: UNSPLASH_CLIENT_ID
            - name: UNSPLASH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: unsplash-username-secret
                  key: UNSPLASH_USERNAME
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 4200
      targetPort: 4200
