name: deploy-client

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCTL_KUBE_CONFIG: ${{ secrets.DOCTL_KUBE_CONFIG }}
      - run: docker build -f ./apps/client/Dockerfile . -t $DOCKER_USERNAME/client
      - run: docker push $DOCKER_USERNAME/client
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save $DOCTL_KUBE_CONFIG
      - run: kubectl rollout restart deployment client-deployment
