name: deploy-client

on:
  push:
    branches:
      - main
    paths:
      - 'apps/client/**'

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -f ./apps/client/Dockerfile . -t webtechnelson/client

      - name: Push Docker image
        run: docker push webtechnelson/client

      - name: Install doctl to manage kubernetes cluster
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: connect to Digital Ocean Kubernetes Cluster
        run: doctl kubernetes cluster kubeconfig save e-commerce

      - name: Redeploy image inside kubernetes cluster
        run: kubectl rollout restart deployment client-deployment
